/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


template <typename T>
class JSI_EXPORT NativeTurboSqliteCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "TurboSqliteCxx";

protected:
  NativeTurboSqliteCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeTurboSqliteCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["openDatabase"] = MethodMetadata {.argCount = 2, .invoker = __openDatabase};
    methodMap_["openDatabaseAsync"] = MethodMetadata {.argCount = 2, .invoker = __openDatabaseAsync};
    methodMap_["getVersionString"] = MethodMetadata {.argCount = 0, .invoker = __getVersionString};
  }
  
private:
  static jsi::Value __openDatabase(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::openDatabase) == 3,
      "Expected openDatabase(...) to have 3 parameters");
    return bridging::callFromJs<jsi::Object>(rt, &T::openDatabase,  static_cast<NativeTurboSqliteCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 || args[1].isUndefined() ? std::nullopt : std::make_optional(args[1].asString(rt)));
  }

  static jsi::Value __openDatabaseAsync(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::openDatabaseAsync) == 3,
      "Expected openDatabaseAsync(...) to have 3 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::openDatabaseAsync,  static_cast<NativeTurboSqliteCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 || args[1].isUndefined() ? std::nullopt : std::make_optional(args[1].asString(rt)));
  }

  static jsi::Value __getVersionString(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getVersionString) == 1,
      "Expected getVersionString(...) to have 1 parameters");
    return bridging::callFromJs<jsi::String>(rt, &T::getVersionString,  static_cast<NativeTurboSqliteCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }
};

} // namespace facebook::react
